export const pageConstant = {
    LAYOUT_HOME: "LAYOUT_HOME",
    LAYOUT_LOGIN: "LAYOUT_LOGIN",
    LAYOUT_ERROR_PAGE: "LAYOUT_ERROR_PAGE",

    LAYOUT_ACCOUNT_PATIENT_MANAGEMENT: "LAYOUT_ACCOUNT_PATIENT_MANAGEMENT",
    LAYOUT_ACCOUNT_DOCTOR_MANAGEMENT: "LAYOUT_ACCOUNT_DOCTOR_MANAGEMENT",

    LAYOUT_SPECIALITY: "LAYOUT_SPECIALITY",

    LAYOUT_CURE_PROCESS: "LAYOUT_CURE_PROCESS",
    LAYOUT_CURE_PROGRESS: "LAYOUT_CURE_PROGRESS",
    
    LAYOUT_CURE_HISTORY: "LAYOUT_CURE_HISTORY",
    LAYOUT_DISEASES: "LAYOUT_DISEASES",
    LAYOUT_PILLS: "LAYOUT_PILLS",
    LAYOUT_NEWS: "LAYOUT_NEWS",
    LAYOUT_PROFILE: "LAYOUT_PROFILE",
}

export const tableConstant = {
    TABLE_DOCTOR_MANAGEMENT: 'TABLE_DOCTOR_MANAGEMENT',
    TABLE_PATIENT_MANAGEMENT: 'TABLE_PATIENT_MANAGEMENT',
}


export const panelTypeConstant = {
    PANEL_CREATE_DOCTOR: 'PANEL_CREATE_DOCTOR',
    PANEL_CREATE_PATIENT: 'PANEL_CREATE_PATIENT',
    PANEL_EDIT_PATIENT: 'PANEL_EDIT_PATIENT',

    PANEL_CREATE_DISEASES: "PANEL_CREATE_DISEASES",
    PANEL_EDIT_DISEASES: "PANEL_EDIT_DISEASES",

    PANEL_CREATE_MEDICATION: "PANEL_CREATE_MEDICATION",
    PANEL_EDIT_MEDICATION: "PANEL_EDIT_MEDICATION"
}