export const pageConstant = {
    LAYOUT_HOME: "LAYOUT_HOME",
    LAYOUT_LOGIN: "LAYOUT_LOGIN",
    LAYOUT_ERROR_PAGE: "LAYOUT_ERROR_PAGE",

    LAYOUT_ACCOUNT_PATIENT_MANAGEMENT: "LAYOUT_ACCOUNT_PATIENT_MANAGEMENT",
    LAYOUT_ACCOUNT_DOCTOR_MANAGEMENT: "LAYOUT_ACCOUNT_DOCTOR_MANAGEMENT",

    LAYOUT_SPECIALITY: "LAYOUT_SPECIALITY",

    LAYOUT_CURE_PROCESS: "LAYOUT_CURE_PROCESS",
    LAYOUT_ON_BOARDING: "LAYOUT_ON_BOARDING",
    LAYOUT_CURE_PROGRESS: "LAYOUT_CURE_PROGRESS",
    
    LAYOUT_CURE_HISTORY: "LAYOUT_CURE_HISTORY",

    LAYOUT_APPOINTMENT: "LAYOUT_APPOINTMENT",
    LAYOUT_DOCTORAPPOINTMENT: "LAYOUT_DOCTORAPPOINTMENT",

    LAYOUT_DISEASES: "LAYOUT_DISEASES",
    LAYOUT_MEDICATION: "LAYOUT_MEDICATION",
    LAYOUT_PROFILE: "LAYOUT_PROFILE",
    LAYOUT_PASSWORD_CHANGE: "LAYOUT_PASSWORD_CHANGE",
    
    LAYOUT_NEWS: "LAYOUT_NEWS",
    LAYOUT_NEWS_POST: 'LAYOUT_NEWS_POST',
    LAYOUT_NEWS_CREATE: 'LAYOUT_NEWS_CREATE',
    LAYOUT_NEWS_REVIEW: "LAYOUT_NEWS_REVIEW"
}

export const tableConstant = {
    TABLE_DOCTOR_MANAGEMENT: 'TABLE_DOCTOR_MANAGEMENT',
    TABLE_PATIENT_MANAGEMENT: 'TABLE_PATIENT_MANAGEMENT',
}


export const panelTypeConstant = {
    PANEL_CREATE_DOCTOR: 'PANEL_CREATE_DOCTOR',
    PANEL_CREATE_PATIENT: 'PANEL_CREATE_PATIENT',
    PANEL_EDIT_PATIENT: 'PANEL_EDIT_PATIENT',

    PANEL_CREATE_DISEASES: "PANEL_CREATE_DISEASES",
    PANEL_EDIT_DISEASES: "PANEL_EDIT_DISEASES",

    PANEL_CREATE_MEDICATION: "PANEL_CREATE_MEDICATION",
    PANEL_EDIT_MEDICATION: "PANEL_EDIT_MEDICATION"
}