export const pageConstant = {
    LAYOUT_HOME: "LAYOUT_HOME",
    LAYOUT_LOGIN: "LAYOUT_LOGIN",
    LAYOUT_ERROR_PAGE: "LAYOUT_ERROR_PAGE",
    LAYOUT_ACCOUNT: "LAYOUT_ACCOUNT",
    LAYOUT_ACCOUNT_CREATE_DOCTOR: "LAYOUT_ACCOUNT_CREATE_DOCTOR",
    LAYOUT_SPECIALITY: "LAYOUT_SPECIALITY",
    LAYOUT_CURE_HISTORY: "LAYOUT_CURE_HISTORY",
    LAYOUT_DISEASES: "LAYOUT_DISEASES",
    LAYOUT_PILLS: "LAYOUT_PILLS",
    LAYOUT_NEWS: "LAYOUT_NEWS",
    LAYOUT_PROFILE: "LAYOUT_PROFILE",
    LAYOUT_CURE_PROCESS: "LAYOUT_CURE_PROCESS"

}